# Site settings
name: Sutanlab Blog
title: Sutan Nst. - Coder
description: A blog and journal about Sutan Nst, Junior Developer
baseurl: "/jekyll-starter-blog" # the subpath for this project default is ""
url: "https://sutanlab.js.org" # the base hostname & protocol in your domain

# Author Settings
username: Sutan Nst.
user_description: Learner, Coder & Coffee Maniac
user_title: Welcome to My Blog Site
avatar: /assets/img/sutan.jpeg
email: sutan.gnst@gmail.com
github_username: sutanlab
disqus_username: sutanlab
facebook_username: sgnzst
instagram_username: sutan_gnst
twitter_username: sutan_gnst
medium_username: sutan.gnst
gplus_username: u/0/112138172681575865281

# Build settings
timezone: Asia/Jakarta
published: true
future: true
show_drafts: false
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About
    url: /about

# plugins
plugins: [ jekyll-paginate-v2, jekyll-feed ]

# exclude my node related stuff
exclude: [
  '.bundle',
  '.publish',
  '_drafts',
  'node_modules',
  'vendor',
  'src',
  'post.sh',
  'deploy.sh',
  'gulpfile.js',
  'package.json',
  'package-lock.json',
  'Gemfile',
  'Gemfile.lock',
  'README.md'
]

# pagination config
pagination:
  enabled: true
  debug: false
  per_page: 5
  sort_reverse: true
  sort_field: 'date'
  paginate_path: /page/:num/
  permalink: '/page/:num/'
  title: ':title'
